{
 "title": "Citus",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": { "query": "query_result(pg_up)" } },
   {
    "name": "table_name",
    "label": "table_name",
    "query": {
     "query": "query_result(citus_citus_tables_shard_count)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Parametres", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Citus params",
   "type": "stat",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "citus_pg_dist_colocation_shardcount{instance=\"$instance\"}",
     "legendFormat": "shards_count"
    },
    {
     "expr": "citus_pg_dist_colocation_replicationfactor{instance=\"$instance\"}",
     "legendFormat": "replication factor"
    },
    {
     "expr": "citus_pg_dist_rebalance_strategy_default_threshold{instance=\"$instance\",name=\"by_shard_count\"}",
     "legendFormat": "rebalance strategy: by_shard_count"
    },
    {
     "expr": "citus_pg_dist_rebalance_strategy_default_threshold{instance=\"$instance\",name=\"by_disk_size\"}",
     "legendFormat": "rebalance strategy: by_disk_size"
    },
    {
     "expr": "citus_pg_dist_rebalance_strategy_minimum_threshold{instance=\"$instance\",name=\"by_shard_count\"}",
     "legendFormat": "rebalance strategy min: by_shard_count"
    },
    {
     "expr": "citus_pg_dist_rebalance_strategy_minimum_threshold{instance=\"$instance\",name=\"by_disk_size\"}",
     "legendFormat": "rebalance strategy min: by_disk_size"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "citus nodes",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "topk(10,count by(groupid,nodename,isactive,noderole,metadatasynced,noderack,shouldhaveshards) (citus_pg_dist_node_nodeid{instance=\"$instance\"}))",
       "legendFormat": "{groupid}"
      }
     ]
    },
    {
     "title": "table sharding",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "topk(10,count by (citus_table_type,distribution_column,colocation_id,table_name,table_owner,table_size,citus_table_type) (citus_citus_tables_shard_count{instance=\"$instance\"}))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Table distributed by nodename",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Distributed by nodename $table_name",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "repeat": "table_name",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10000,sum by (nodename) (citus_citus_shards_shard_size{instance=\"$instance\",table_name=~\"$table_name\"}))",
       "legendFormat": "{{nodename}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Table distributed by  shards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Distributed by nodename $table_name",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "repeat": "table_name",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10000,sum by (shard_name) (citus_citus_shards_shard_size{instance=\"$instance\",table_name=~\"$table_name\"}))",
       "legendFormat": "{{shard_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "top iowait queries",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "topk(10,count by (query) (citus_dist_stats_activity_worker_top_waits_queries_count{instance=\"$instance\"}))",
       "legendFormat": "{{query}}"
      }
     ]
    },
    {
     "title": "queries from clients by servers",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "topk(10,sum by (client_addr,server) (citus_dist_stats_activity_worker_connections_by_client_cnt{instance=\"$instance\"}))",
       "legendFormat": "{{query}}"
      }
     ]
    }
   ]
  }
 ]
}