{
 "title": "Yandex Odyssey",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": { "query": "query_result(user_len)" } },
   { "name": "user", "label": "user", "query": { "query": "query_result(avg_query_count)" } }
  ]
 },
 "panels": [
  {
   "title": "client_pool_total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(client_pool_total{job=\"odyssey\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "clients_processed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(clients_processed{job=\"odyssey\",instance=\"$instance\"}[5m])",
     "legendFormat": "clients_processed {{worker}}"
    }
   ]
  },
  {
   "title": "server pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "server_pool_active{job=\"odyssey\",instance=~\"$instance\"}",
     "legendFormat": "server_pool_active"
    },
    {
     "expr": "sever_pool_idle{job=\"odyssey\",instance=~\"$instance\"}",
     "legendFormat": "sever_pool_idle"
    }
   ]
  },
  {
   "title": "Count tx/queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "avg_tx_count{job=\"odyssey\",instance=\"$instance\",user=~\"$user\"}",
     "legendFormat": "{{user}} tx"
    },
    {
     "expr": "avg_query_count{job=\"odyssey\",instance=\"$instance\",user=~\"$user\"}",
     "legendFormat": "{{user}} queries"
    }
   ]
  },
  {
   "title": "Average transaction time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg_tx_time{job=\"odyssey\",instance=\"$instance\",user=~\"$user\"}",
     "legendFormat": "{{user}} tx_time"
    }
   ]
  },
  {
   "title": "Average in/out bytes/sec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(avg_recv_client{job=\"odyssey\",instance=\"$instance\",user=~\"$user\"})",
     "legendFormat": "{{user}} client traffic in"
    },
    {
     "expr": "sum(avg_recv_server{job=\"odyssey\",instance=\"$instance\",user=~\"$user\"})",
     "legendFormat": "{{user}} client traffic out"
    }
   ]
  }
 ]
}